### ISSUE TITLE
Update or add new examples that is validatable

### ISSUE THREAD

**Issue by erdtman** [erwah/ietf#13]
it should be possible to put the examples in a CWT implementation and validate them.

This requires the key material to be added to.

**Comment by selfissued** [comment]
I would also advocate having at least one example that uses only the claims defined by CWT.  This means that it wouldn't use "cks", for instance.

**Comment by selfissued** [comment]
The examples in https://tools.ietf.org/html/draft-ietf-ace-cbor-web-token-03 can be validated.
