### ISSUE TITLE
Evaluate recomendation of AEAD in create section.

### ISSUE THREAD

**Issue by erdtman** [erwah/ietf#24]
Comment from Jim:
"8.  The note for step 5 in section 6.1 is problematic from a number of
things.  A) AEAD algorithms are required, so it is not clear that the
recommendation makes sense.  B) there is a big difference between signing
and MACing in terms of the amount and type of integrity provided.  Replacing
signing w/ AEAD loses a lot."

**Comment by selfissued** [comment]
Let's just delete the note.  I think it adds more confusion than clarity.

**Comment by selfissued** [comment]
The note was deleted in PR #31 .
