### ISSUE TITLE
use a TBD for the CWT tag rather than using a constant so this is highlighted

### ISSUE THREAD

**Issue by erdtman** [erwah/ietf#25]

**Comment by selfissued** [comment]
As I'm writing in my reply to Jim's review, I disagree with doing this.  The values in the registry are already marked as “TBD (maybe 61)”.  It would just add clutter, detracting from the readability of the spec, to replicate this elsewhere.  Besides, the examples need a specific number.  If IANA changes the number, we will of course, update the spec accordingly, once a final assignment is determined.

**Comment by selfissued** [comment]
I will apply for early registration of the CBOR Tag and Content-Type numbers to address this issue once WGLC starts.

**Comment by erdtman** [comment]
Closing as wont fix for now

**Comment by selfissued** [comment]
I applied for the IANA registrations.  It is request ID [IANA #967179].
