### ISSUE TITLE
Review and update create and verify steps

### ISSUE THREAD

**Issue by erdtman** [erwah/ietf#27]
Comment form Jim:
"9.  Step 6 in section 6.1 does not agree w/ the language in section 5.  MUST
vs maybe."

**Comment by selfissued** [comment]
As I'm writing in my reply to Jim, Section 5 says that use of the CBOR tag is optional.  But I see that the language “The CWT tag MUST prefix a tagged object” could be misinterpreted.  I think we should change this to “If present, the CWT tag MUST prefix a tagged object”.

**Comment by selfissued** [comment]
I just pushed this fix to master.
