### ISSUE TITLE
Split Security Considerations

### ISSUE THREAD

**Issue by erdtman** [erwah/ietf#36]
* Break section Security Considerations into multiple paragraphs that deal with different types of
issues.

* In section 8, the first sentence implies to me that you believe that COSE
is more of a problem that breaking of cryptographic algorithms, trust of
certificates/keys.  Not sure what needs to be done, but better clarity may
be a good idea.

**Comment by selfissued** [comment]
Change "The security of the CWT is dependent on the protections offered by COSE" to "The security of the CWT relies upon on the protections offered by COSE".

I'd add a paragraph break before "Since the claims".
