### ISSUE TITLE
Enable use of string lables

### ISSUE THREAD

**Issue by erdtman** [erwah/ietf#38]
T2: The spec doesn't clearly say that entry labels MUST be unsigned
numbers.  It could simply say that, but this creates an X-Dash
problem: Since people who want to experiment with CWT need to invent
numbers, they will, and there will be squatting galore.  CBOR actually
provides a nice way to solve this problem: Allow text strings as claim
labels for experimentation, replacing the need for a provisional
registration for each experiment.  No "production" CWT should have a
text label, of course; this is extremely easy to check.

**Comment by selfissued** [comment]
I agree that we should allow the use of string-valued labels.  However, I disagree with the suggestion that we somehow limit string-valued labels to non-production uses.  Instead, we should allow strings to be registered in the CWT Claims registry, just like numbers can be registered.
