### ISSUE TITLE
Look into why CBOR Key Value range is defined as is.

### ISSUE THREAD

**Issue by erdtman** [erwah/ietf#40]
T5: The range 1 to 65536 is a seriously weird range.  If we do allow
one value that requires a four-byte representation then why not go for
1..4294967295?

**Comment by selfissued** [comment]
We should allow unsigned integers, negative integers, and strings - mirroring this language from COSE section 1.4:

`In COSE, we use strings, negative integers and unsigned integers as map keys.`

Likewise, we probably also want to incorporate this language from COSE:

`Integer values between -256 and 255 and strings of length 1 are designated as Standards Track Document required.  Integer values from -65536 to 65535 and strings of length 2 are designated as Specification Required.  Integer values of greater than 65535 and strings of length greater than 2 are designated as expert review.  Integer values less than -65536 are marked as private use.`

We should add an IANA entry for the value 0 saying that it is reserved.
