### ISSUE TITLE
Add example with real type time value

### ISSUE THREAD

**Issue by erdtman** [erwah/ietf#44]
* I have not done any validation of the examples.   You might want to have
an example which uses the real for one of the time types.

[JLS] Use the value of “1444064944.5” for one of the time values.  Although I doubt that less than second resolution is needed in almost any case, having an example where it is given is still a good idea.

**Comment by selfissued** [comment]
This is a nice-to-have, if it's straightforward to do.  That said, I wouldn't include it in the signed CWT that's used in the body of the nested CWT.  That one should be indicative of what we think will actually be done.  The floating point example should probably be a new example - possibly one with only an "iat" claim that specifies a non-integer time.
