### ISSUE TITLE
Address Jim Schaad's inability to reproduce the examples

### ISSUE THREAD

**Issue by selfissued** [erwah/ietf#62]
See the thread "[Ace] I-D Action: draft-ietf-ace-cbor-web-token-05.txt".  The editorial comments that he made have been addressed in -06 but his problems with the examples have not been.

Samuel, can you please have a look at this one?

**Comment by selfissued** [comment]
For some reason I couldn't assign this issue to @erdtman.

**Comment by erdtman** [comment]
I can´t either but I´m on it.

**Comment by selfissued** [comment]
This was addressed through incorporating Carsten Bormann's review feedback in draft-ietf-ace-cbor-web-token-08.
